default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gem_force_dev1_development

test:
  <<: *default
  database: gem_force_dev1_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>


  queue:
    <<: *default
    url: <%= ENV["QUEUE_DATABASE_URL"] %>

  prosper_external:
    <<: *default
    url: <%= ENV["PROSPER_DB_URL"] %>
    sslmode: require

  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL", ENV["DATABASE_URL"]) %>
